<?php

namespace Tests\Feature\Academic;

use App\Models\AcademicSession;
use App\Models\AdmissionApplication;
use App\Models\Applicant;
use App\Models\Branch;
use App\Models\ClassSection;
use App\Models\Form;
use App\Models\GradeScale;
use App\Models\Mark;
use App\Models\SchoolSetting;
use App\Models\Sequence;
use App\Models\Student;
use App\Models\StudentEnrollment;
use App\Models\StudentSubject;
use App\Models\Subject;
use App\Models\Term;
use App\Models\TermResult;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

/**
 * Report cards were the only document the system could produce. The acceptance
 * letter, leaving certificate, cumulative record and class marksheet — the four
 * things a school office is actually asked for — were all generated by hand.
 */
class StudentDocumentsTest extends TestCase
{
    use RefreshDatabase;

    private Branch $branch;
    private AcademicSession $session;
    private Term $term;
    private Form $form;
    private ClassSection $section;
    private Subject $maths;
    private Subject $english;
    private Sequence $sequence;

    protected function setUp(): void
    {
        parent::setUp();

        $this->branch = Branch::firstOrCreate(['code' => 'MAIN'], ['name' => 'Main', 'is_active' => true]);

        $admin = User::create([
            'first_name' => 'Ada', 'last_name' => 'Admin',
            'email' => 'admin@example.test', 'password' => 'password',
            'role' => 'super_admin', 'is_active' => true,
        ]);
        $admin->branches()->attach($this->branch->id, ['is_default' => true]);
        $this->actingAs($admin);

        SchoolSetting::create([
            'branch_id' => $this->branch->id,
            'school_name' => 'Test College', 'school_code' => 'TC',
        ]);

        $this->session = AcademicSession::create([
            'branch_id' => $this->branch->id, 'name' => '2025/2026',
            'start_date' => '2025-09-01', 'end_date' => '2026-07-31',
            'status' => 'active', 'is_current' => true,
        ]);
        $this->term = Term::create([
            'branch_id' => $this->branch->id, 'term_number' => 1, 'name' => 'First Term',
            'start_date' => '2025-09-01', 'end_date' => '2025-12-15', 'is_current' => true,
        ]);
        $this->form = Form::create([
            'branch_id' => $this->branch->id, 'name' => 'Form 1', 'short_name' => 'F1',
            'level' => 'first_cycle', 'school_level' => 'secondary',
            'has_streams' => false, 'display_order' => 1, 'is_active' => true,
        ]);
        $this->section = ClassSection::create([
            'branch_id' => $this->branch->id, 'form_id' => $this->form->id,
            'section' => 'A', 'name' => 'Form 1A', 'max_students' => 40, 'is_active' => true,
        ]);

        $this->maths = $this->subject('Maths', 'MTH', 4);
        $this->english = $this->subject('English', 'ENG', 2);

        $this->sequence = Sequence::create([
            'branch_id' => $this->branch->id, 'name' => 'Seq 1', 'sequence_number' => 1, 'weight' => 1,
        ]);
        DB::table('form_sequence')->insert([
            'form_id' => $this->form->id, 'term_id' => $this->term->id, 'sequence_id' => $this->sequence->id,
        ]);

        GradeScale::create([
            'branch_id' => $this->branch->id, 'grade' => 'A',
            'min_mark' => 0, 'max_mark' => 20, 'description' => 'Pass', 'display_order' => 1,
        ]);
    }

    private function subject(string $name, string $code, float $coefficient): Subject
    {
        $subject = Subject::create([
            'branch_id' => $this->branch->id, 'name' => $name, 'code' => $code, 'is_active' => true,
        ]);

        DB::table('form_subject')->insert([
            'form_id' => $this->form->id, 'subject_id' => $subject->id,
            'coefficient' => $coefficient, 'type' => 'core',
        ]);

        return $subject;
    }

    private function student(string $first, string $id, string $status = 'active'): Student
    {
        return Student::create([
            'branch_id' => $this->branch->id, 'student_id' => $id,
            'first_name' => $first, 'last_name' => 'Test',
            'date_of_birth' => '2012-01-01', 'gender' => 'female',
            'status' => $status, 'admission_date' => '2025-09-01',
        ]);
    }

    private function enrol(Student $student): StudentEnrollment
    {
        $enrollment = StudentEnrollment::create([
            'branch_id' => $this->branch->id, 'student_id' => $student->id,
            'academic_session_id' => $this->session->id, 'term_id' => $this->term->id,
            'class_section_id' => $this->section->id, 'residence_type' => 'day',
            'enrollment_date' => '2025-09-01', 'status' => 'active',
        ]);

        foreach ([[$this->maths, 4], [$this->english, 2]] as [$subject, $coefficient]) {
            StudentSubject::create([
                'branch_id' => $this->branch->id,
                'student_enrollment_id' => $enrollment->id,
                'subject_id' => $subject->id, 'coefficient' => $coefficient,
            ]);
        }

        return $enrollment;
    }

    private function mark(StudentEnrollment $enrollment, Subject $subject, float $score): void
    {
        Mark::create([
            'branch_id' => $this->branch->id,
            'student_enrollment_id' => $enrollment->id,
            'subject_id' => $subject->id,
            'sequence_id' => $this->sequence->id,
            'score' => $score, 'is_absent' => false, 'status' => 'approved',
        ]);
    }

    private function application(string $status): AdmissionApplication
    {
        $applicant = Applicant::create([
            'first_name' => 'Ann', 'last_name' => 'Applicant',
            'email' => 'ann@example.test', 'password' => 'password',
        ]);

        return AdmissionApplication::create([
            'branch_id' => $this->branch->id,
            'applicant_id' => $applicant->id,
            'application_number' => 'APP-0001',
            'academic_session_id' => $this->session->id,
            'form_id' => $this->form->id,
            'first_name' => 'Ann', 'last_name' => 'Applicant',
            'date_of_birth' => '2012-01-01', 'gender' => 'female',
            'emergency_contact_name' => 'Guardian', 'emergency_contact_phone' => '670000000',
            'status' => $status,
        ]);
    }

    // ------------------------------------------------------ acceptance letter

    public function test_an_acceptance_letter_is_refused_before_the_place_is_granted(): void
    {
        $application = $this->application('pending');

        // A letter for an application nobody accepted would commit the school to
        // a place it has not granted.
        $this->get(route('admin.documents.acceptance-letter', $application))
            ->assertRedirect();

        $this->assertNotNull(session('error'));
    }

    public function test_an_accepted_application_produces_a_letter(): void
    {
        $application = $this->application('accepted');

        $this->get(route('admin.documents.acceptance-letter', $application))
            ->assertSuccessful()
            ->assertHeader('content-type', 'application/pdf');
    }

    // --------------------------------------------------- leaving certificate

    public function test_a_leaving_certificate_is_refused_for_a_student_still_here(): void
    {
        $student = $this->student('Ben', 'MAIN0002');

        $this->get(route('admin.documents.leaving-certificate', $student))
            ->assertRedirect();

        $this->assertNotNull(session('error'));
    }

    public function test_a_graduated_student_gets_a_leaving_certificate(): void
    {
        $student = $this->student('Cid', 'MAIN0003', 'graduated');
        $this->enrol($student);

        $this->get(route('admin.documents.leaving-certificate', $student))
            ->assertSuccessful()
            ->assertHeader('content-type', 'application/pdf');
    }

    // ----------------------------------------------------- cumulative record

    public function test_a_cumulative_record_renders_the_students_history(): void
    {
        $student = $this->student('Dee', 'MAIN0004');
        $enrollment = $this->enrol($student);

        TermResult::create([
            'student_enrollment_id' => $enrollment->id,
            'term_id' => $this->term->id,
            'term_average' => 13.5, 'class_rank' => 2, 'total_students' => 30,
        ]);

        $this->get(route('admin.documents.cumulative-record', $student))
            ->assertSuccessful()
            ->assertHeader('content-type', 'application/pdf');
    }

    public function test_a_cumulative_record_works_for_a_student_with_no_results(): void
    {
        $student = $this->student('Eve', 'MAIN0005');

        // A brand-new student must not crash the document.
        $this->get(route('admin.documents.cumulative-record', $student))
            ->assertSuccessful();
    }

    // ------------------------------------------------------- class marksheet

    public function test_the_marksheet_shows_every_subject_for_the_class(): void
    {
        $ann = $this->enrol($this->student('Ann', 'MAIN0006'));
        $bob = $this->enrol($this->student('Bob', 'MAIN0007'));

        $this->mark($ann, $this->maths, 16);
        $this->mark($ann, $this->english, 10);
        $this->mark($bob, $this->maths, 8);
        $this->mark($bob, $this->english, 14);

        $response = $this->get(route('admin.documents.marksheet', [
            'academic_session_id' => $this->session->id,
            'form_id' => $this->form->id,
            'class_section_id' => $this->section->id,
            'term_id' => $this->term->id,
        ]))->assertSuccessful();

        $rows = $response->viewData('rows');

        $this->assertCount(2, $rows);
        $this->assertCount(2, $response->viewData('subjects'));

        // Ann: (16*4 + 10*2)/6 = 14.00. Bob: (8*4 + 14*2)/6 = 10.00.
        // Ranked, so Ann leads.
        $this->assertEquals(14.0, $rows[0]->average);
        $this->assertSame(1, $rows[0]->rank);
        $this->assertEquals(10.0, $rows[1]->average);
        $this->assertSame(2, $rows[1]->rank);
    }

    public function test_the_marksheet_csv_carries_a_bom_and_the_grid(): void
    {
        $ann = $this->enrol($this->student('Ann', 'MAIN0008'));
        $this->mark($ann, $this->maths, 16);
        $this->mark($ann, $this->english, 10);

        $response = $this->get(route('admin.documents.marksheet.csv', [
            'academic_session_id' => $this->session->id,
            'class_section_id' => $this->section->id,
            'term_id' => $this->term->id,
        ]))->assertSuccessful();

        $csv = $response->streamedContent();

        // Without the BOM, Excel reads UTF-8 as Latin-1 and mangles every
        // accented name in a francophone school.
        $this->assertStringStartsWith("\xEF\xBB\xBF", $csv);
        // Columns follow the form's curriculum in name order, so English
        // precedes Maths whatever order the marks were entered in.
        $this->assertStringContainsString('"English (x2)","Maths (x4)"', $csv);

        // Values go out unformatted so a spreadsheet reads them as numbers
        // rather than as text.
        $this->assertStringContainsString('MAIN0008,"Ann Test",10,16', $csv);
    }

    public function test_the_marksheet_pdf_renders(): void
    {
        $ann = $this->enrol($this->student('Ann', 'MAIN0009'));
        $this->mark($ann, $this->maths, 16);

        $this->get(route('admin.documents.marksheet.pdf', [
            'academic_session_id' => $this->session->id,
            'class_section_id' => $this->section->id,
            'term_id' => $this->term->id,
        ]))->assertSuccessful()->assertHeader('content-type', 'application/pdf');
    }

    public function test_the_marksheet_screen_loads_with_nothing_chosen(): void
    {
        $this->get(route('admin.documents.marksheet'))->assertSuccessful();
    }
}
